/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.adm.Adm;
import br.edu.ifnmg.adm.AdmDao;
import br.edu.ifnmg.credential.Credential;
import br.edu.ifnmg.librarian.Librarian;
import br.edu.ifnmg.librarian.LibrarianDao;
import br.edu.ifnmg.reader.Reader;
import br.edu.ifnmg.reader.ReaderDao;
import br.edu.ifnmg.role.Role;
import br.edu.ifnmg.role.RoleDao;
import java.time.LocalDate;
import java.time.ZoneId;

/**
 *
 * @author joaok
 */
public class CadrastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadrastroUsuario
     */
    private static CadrastroUsuario instance;

    public CadrastroUsuario() {
        initComponents();
        // Centralização da janela
        setLocationRelativeTo(null);
        lblCadastro.setVisible(false);
        lblIncorreto.setVisible(false);
    }

    public static CadrastroUsuario getInstance() {
        if (instance == null) {
            instance = new CadrastroUsuario();
        }
        instance.setAlwaysOnTop(true);
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private LocalDate getSelectedDate(com.toedter.calendar.JDateChooser dateChooser) {
        if (dateChooser.getDate() != null) {
            return dateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        }
        return LocalDate.now();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        PanelCadrastro = new javax.swing.JPanel();
        lblPapel = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pwdSenha = new javax.swing.JTextField();
        chkAtivo = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblAniversario = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        calDate = new com.toedter.calendar.JDateChooser();
        boxPapel = new javax.swing.JComboBox<>();
        lblCadastro = new javax.swing.JLabel();
        lblIncorreto = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadrastro Usuário");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblPapel.setText("Papel:");

        lblUsuario.setText("Usuário:");

        lblSenha.setText("Senha:");

        chkAtivo.setText("Ativo");

        lblNome.setText("Nome:");

        lblEmail.setText("Email:");

        lblAniversario.setText("Data de Aniversario:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        boxPapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Bibliotecário", "Leitor" }));

        lblCadastro.setForeground(new java.awt.Color(0, 0, 255));
        lblCadastro.setText("Usuário Cadastrado!!");

        lblIncorreto.setForeground(new java.awt.Color(240, 0, 0));
        lblIncorreto.setText("Campos Indefinidos Troque-os!!");

        javax.swing.GroupLayout PanelCadrastroLayout = new javax.swing.GroupLayout(PanelCadrastro);
        PanelCadrastro.setLayout(PanelCadrastroLayout);
        PanelCadrastroLayout.setHorizontalGroup(
            PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCadrastroLayout.createSequentialGroup()
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadrastroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSenha)
                                    .addComponent(lblUsuario)
                                    .addComponent(lblPapel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                        .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(pwdSenha))
                                        .addGap(83, 83, 83)
                                        .addComponent(chkAtivo))
                                    .addComponent(boxPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblNome))
                                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(txtEmail))
                                    .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadrastroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCadrastroLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAniversario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelCadrastroLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(lblIncorreto)))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
        );
        PanelCadrastroLayout.setVerticalGroup(
            PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCadrastroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPapel)
                    .addComponent(boxPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(pwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAtivo))
                .addGap(58, 58, 58)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAniversario)
                    .addComponent(calDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblIncorreto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCadrastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(lblCadastro))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCadrastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelCadrastro, javax.swing.GroupLayout.PREFERRED_SIZE, 406, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
            Role role = new Role(boxPapel.getSelectedItem().toString());
            Long role_id = new RoleDao().saveOrUpdate(role);
            role.setId(role_id);

            Credential cred1 = new Credential();
            cred1.setId(null);
            cred1.setUsername(txtUsuario.getText());
            cred1.setPassword(pwdSenha.getText());
            cred1.setLastAccess(LocalDate.now());
            cred1.setEnabled(chkAtivo.isSelected());
            if (boxPapel.getSelectedItem().toString().equals("Bibliotecário")) {
                Librarian ana = null;
                ana = new Librarian();
                ana.setName(txtNome.getText());
                ana.setEmail(txtEmail.getText());
                ana.setBirthDate(getSelectedDate(calDate));
                ana.setRole(role);
                ana.setCredential(cred1);

                cred1.setUser(ana);
                Long user_id = new LibrarianDao().saveOrUpdate(ana);

                Librarian L = null;
                L = new LibrarianDao().findById(user_id);
                new LibrarianDao().saveOrUpdate(L);
                System.out.println("Bibliotecário Cadastrado!!");
                instance.setAlwaysOnTop(false);
                lblCadastro.setVisible(true);
//                this.setVisible(false);
//                TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
                System.out.println(L.toString());
            } else if (boxPapel.getSelectedItem().toString().equals("Leitor")) {
                Reader joao = null;
                joao = new Reader();
                joao.setName(txtNome.getText());
                joao.setEmail(txtEmail.getText());
                joao.setBirthDate(getSelectedDate(calDate));
                joao.setRole(role);
                joao.setCredential(cred1);
                joao.getCredential().setUser(joao);
                Long user_id = new ReaderDao().saveOrUpdate(joao);

                joao = new ReaderDao().findById(user_id);
                new ReaderDao().saveOrUpdate(joao);
                instance.setAlwaysOnTop(false);
                System.out.println("Leitor Cadastrado!!");
                lblCadastro.setVisible(true);
//                this.setVisible(false);
//                TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
                System.out.println(joao.toString());
            } else if (boxPapel.getSelectedItem().toString().equals("Administrador")) {
                Adm adm = null;
                adm = new Adm();
                adm.setName(txtNome.getText());
                adm.setEmail(txtEmail.getText());
                adm.setBirthDate(getSelectedDate(calDate));
                adm.setRole(role);
                adm.setCredential(cred1);
                adm.getCredential().setUser(adm);
                Long user_id = new AdmDao().saveOrUpdate(adm);

                adm = new AdmDao().findById(user_id);
                new AdmDao().saveOrUpdate(adm);
                instance.setAlwaysOnTop(false);
                System.out.println("Administrador Cadastrado!!");
                lblCadastro.setVisible(true);
//                this.setVisible(false);
//                TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
                System.out.println(adm.toString());
            }
            boxPapel.setSelectedIndex(0);
            txtUsuario.setText("");
            pwdSenha.setText("");
            chkAtivo.setSelected(false);
            txtNome.setText("");
            txtEmail.setText("");
            calDate.setDate(null);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            lblIncorreto.setVisible(true);
            lblCadastro.setVisible(false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        boxPapel.setSelectedIndex(0);
        txtUsuario.setText("");
        pwdSenha.setText("");
        chkAtivo.setSelected(false);
        txtNome.setText("");
        txtEmail.setText("");
        calDate.setDate(null);
        lblCadastro.setVisible(false);
        lblIncorreto.setVisible(false);
//        this.setVisible(false);
//        TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadrastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadrastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadrastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadrastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadrastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCadrastro;
    private javax.swing.JComboBox<String> boxPapel;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calDate;
    private javax.swing.JCheckBox chkAtivo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel lblAniversario;
    private javax.swing.JLabel lblCadastro;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIncorreto;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPapel;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField pwdSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
