/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.commets.Comments;
import br.edu.ifnmg.commets.CommentsDao;
import br.edu.ifnmg.credential.Credential;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author joaok
 */
public class DeleteComentarios extends javax.swing.JFrame {

    /**
     * Creates new form ComentariosLivro
     */
    private static DeleteComentarios instance;
    public static Credential cred = null;

//    private Long selectedCommentId;
    public DeleteComentarios() {
        initComponents();
        // Centralização da janela
        setLocationRelativeTo(null);
        lblApagado.setVisible(false);
        lblSelecione.setVisible(false);
        DeleteComentariosTable();
        ocultarColunaId();
    }

    public static DeleteComentarios getInstance() {
        if (instance == null) {
            instance = new DeleteComentarios();
        }
        return instance;
    }

    private void ocultarColunaId() {
        int columnIndex = 0;
        TableColumn colunaId = tableDelComentarios.getColumnModel().getColumn(columnIndex);
        colunaId.setMinWidth(0);
        colunaId.setMaxWidth(0);
        colunaId.setPreferredWidth(0);
        colunaId.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDelete = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDelComentarios = new javax.swing.JTable();
        lblTdsLivros = new javax.swing.JLabel();
        lblSelecione = new javax.swing.JLabel();
        lblApagado = new javax.swing.JLabel();
        btnComentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Apagar Comentários");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tableDelComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Titulo", "Autor", "Comentário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDelComentarios);

        lblTdsLivros.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTdsLivros.setText("Meus Comentários ");

        lblSelecione.setForeground(new java.awt.Color(240, 0, 0));
        lblSelecione.setText("Selecione um Comentário!!");

        lblApagado.setForeground(new java.awt.Color(0, 0, 255));
        lblApagado.setText("Comentário Apagado Com Sucesso!!");

        btnComentar.setText("Apagar");
        btnComentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnComentar)
                    .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDeleteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDeleteLayout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addComponent(lblTdsLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDeleteLayout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(lblSelecione))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblApagado, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(lblTdsLivros)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelecione)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblApagado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnComentar)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lblSelecione.setVisible(false);
        lblApagado.setVisible(false);

//        this.setVisible(false);
//        TelaPrincipal.getInstance(TelaPrincipal.current_cred).setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnComentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableDelComentarios.getSelectedRow();
        if (selectedRow != -1) {
            // Obtém o título da coluna 'Titulo' na linha clicada
//            DeleteComentarios(selectedCommentId);
            Long selectedId = (Long) tableDelComentarios.getValueAt(selectedRow, 0);
            DeleteComentarios(selectedId);

            DeleteComentariosTable();
        } else {
            System.out.println("Selecione pelo menos um comentário antes de apagar.");
            lblSelecione.setVisible(true);
        }
    }//GEN-LAST:event_btnComentarActionPerformed

    private void DeleteComentariosTable() {
        try {
            CommentsDao commentsDao = new CommentsDao();
            List<Comments> allComments = commentsDao.findAll();

            DefaultTableModel model = (DefaultTableModel) tableDelComentarios.getModel();
            model.setRowCount(0);

            for (Comments comments : allComments) {
                Long readerId = cred.getUser().getId();
                if (comments.getReader().getId().equals(readerId)) {
                    Object[] rowData = {
                        comments.getId(),
                        comments.getBook().getTitle(),
                        comments.getBook().getAuthors(),
                        comments.getComentarios()
                    };
                    model.addRow(rowData);

                    // Adiciona um ouvinte para a tabela
                    tableDelComentarios.getSelectionModel().addListSelectionListener(e -> {
                        int selectedRow = tableDelComentarios.getSelectedRow();
                        if (selectedRow != -1) {
//                            selectedCommentId = comments.getId();

                            lblSelecione.setVisible(false);
                            lblApagado.setVisible(false);
                        }
                    });
                }
            }
            tableDelComentarios.repaint();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void DeleteComentarios(Long selectedId) {
        try {
            if (selectedId != null) {
                new CommentsDao().delete(selectedId);
                System.out.println("Comentario '" + selectedId + "' deletado com sucesso!");
                lblSelecione.setVisible(false);
                lblApagado.setVisible(true);

                // Atualiza a tabela após a exclusão
                DeleteComentariosTable();
            } else {
                System.out.println("Selecione um comentario antes de deletar.");
                lblSelecione.setVisible(true);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteComentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApagado;
    private javax.swing.JLabel lblSelecione;
    private javax.swing.JLabel lblTdsLivros;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JTable tableDelComentarios;
    // End of variables declaration//GEN-END:variables
}
