/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.ifnmg.gui;

import br.edu.ifnmg.copy.Copy;
import br.edu.ifnmg.copy.CopyDao;
import br.edu.ifnmg.emprestimo.Emprestimo;
import br.edu.ifnmg.emprestimo.EmprestimoDao;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ketsu
 */
public class HistoricoEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteLivro
     */
    private static HistoricoEmprestimo instance;

    public HistoricoEmprestimo() {
        initComponents();
        // Centralização da janela
        //setLocationRelativeTo(null);
        viewBookTable();
    }

    public static HistoricoEmprestimo getInstance() {
        if (instance == null) {
            instance = new HistoricoEmprestimo();
        }
        instance.viewBookTable();
        TelaPrincipal.getInstance(TelaPrincipal.current_cred).jDesktop.add(instance);
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivro = new javax.swing.JTable();
        lblTdsLivros = new javax.swing.JLabel();

        setClosable(true);

        tableLivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Feito em", "Devolução em", "Livro1", "Livro2", "Livro3"
            }
        ));
        tableLivro.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableLivro);

        lblTdsLivros.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTdsLivros.setText("Histórico de Empréstimos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTdsLivros)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTdsLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewBookTable() {
        try {
            EmprestimoDao dao = new EmprestimoDao();
            CopyDao copyDao = new CopyDao();
            List<Emprestimo> emp = dao.findAll();
            List<Emprestimo> emp_final = new ArrayList<>();
            List<Copy> copies = copyDao.findAll();
            
            for(Emprestimo aux: emp){
                for(Copy copy: copies){
                    if(copy.getEmprestimo()==null) continue;
                    if(Objects.equals(copy.getEmprestimo().getId(), aux.getId())){
                        aux.addCopy(copy);
                    }
                }
            }
            
            for(Emprestimo aux: emp){
                if(Objects.equals(aux.getReader().getId(), TelaPrincipal.current_cred.getUser().getId())){
                    emp_final.add(aux);
                }
            }
            
            DefaultTableModel model = (DefaultTableModel) tableLivro.getModel();
            model.setRowCount(0);
            System.out.println(Arrays.toString(emp_final.toArray()));
            for (Emprestimo aux : emp_final) {
                System.out.println(aux.getCopy(1).getBook());
                Object[] rowData = {
                    aux.getDiaEmprestimo(),
                    aux.getDiaRetorno(),
                    aux.getCopy(0).getBook().getTitle(),
                    aux.getCopy(1).getBook().getTitle(),
                    aux.getCopy(2).getBook().getTitle(),
                };
                model.addRow(rowData);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTdsLivros;
    private javax.swing.JTable tableLivro;
    // End of variables declaration//GEN-END:variables
}
